### ISSUE TITLE
Create polygons from angles

### ISSUE THREAD

**Issue by saraedum** [videlec/sage-flatsurf#10]
It would be nice if we could support the polygon format for specifying surfaces by just providing the angles instead of explicit coordinates.

**Comment by saraedum** [comment]
I can try to implement this if you give me a pointer on how to do this.

**Comment by videlec** [comment]
Be careful than specifying angles do not specify a polygon (angles are invariant under rescaling). You need to specify one length.

What we also want to do is that if the polygon is constructed this way, then we do not want to recompute the angles when calling [`ConvexPolygon.angle()` in polygon.py](https://github.com/videlec/sage-flatsurf/blob/master/flatsurf/geometry/polygon.py#L868-L880) (that ultimately calls the [function angle in matrix_2x2.py](https://github.com/videlec/sage-flatsurf/blob/master/flatsurf/geometry/matrix_2x2.py#L251-L340)).

**Comment by saraedum** [comment]
So I guess this could be added to the `element_constructor` of `ConvexPolygon`. What about something like `Polygons(angles=[1,2,2,1])` which produces a quadrilateral with these angles. There are in general some choices here of course so I guess it's reasonable to just pick edge lengths automatically (without exact-real numbers.)
Alternatively, one can specify edge lengths: `Polygons(angles=[1,2,2,1], lengths=[None, RealNumber.random(), None, None])` which forces a side to have the specified length. The `lengths` are automatically padded with `None` so you can write something like `Polygons(angles=[1,1,1,1], lengths=[RealNumber.random(), RealNumber.random()])` to get a rectangle with random side lenghts.
There's already `triangle(a, b, c)` which would be equivalent to `Polygons(angles=[a,b,c], lengths=[1])` I think.

**Comment by videlec** [comment]
As far as a single polygon is concerned, you need to specify the right number of lengths so that it is well defined (eg one for a triangle, two for a quadrilateral, etc). Indeed, `triangle(a,b,c)` should just be a particular case.

It would also make sense to have families (eg the set of quadrilaterals with angle `[1,2,2,1]`) with possibly some additional constraints (eg sides X and Y are parallel). From these, it should be possible to get random elements. Something like
```
F = flatsurf.MyFamily(...)
surf = F.random_element()
```

**Comment by saraedum** [comment]
> As far as a single polygon is concerned, you need to specify the right number of lengths so that it is well defined (eg one for a triangle, two for a quadrilateral, etc). Indeed, `triangle(a,b,c)` should just be a particular case.

Sure but I guess it's convenient to use some default when no length has been specified? Say, assume length one whenever a choice has to be made?

> It would also make sense to have families (eg the set of quadrilaterals with angle `[1,2,2,1]`) with possibly some additional constraints (eg sides X and Y are parallel). From these, it should be possible to get random elements. Something like
> 
> ```
> F = flatsurf.MyFamily(...)
> surf = F.random_element()
> ```

Sounds like a good second step to me.

**Comment by saraedum** [comment]
One interface should look something like this:
```
Polygon(angles=[1, 2, 2, 1]) -> Family of Surfaces -> an_element(ring=double/RealNumber/long long)
Polygon(angles=[1, 2, 2, 1], lengths=[RealNumber.random(1, 3)]) -> Family of Surfaces 
```

The underlying low level format would probably be this:
```
Family = FlatTriangulation<AA[x,y,z,…]> + 1 example = FlatTriangulation<Element>
```
see polygon (equalities from triangles, inequalities from positive area, connected)

**Comment by videlec** [comment]
The library now supports the syntax
```
sage: flatsurf.polygons(angles=[1,1,2,3], lengths=[3/2,1])
Polygon: (0, 0), (3/2, 0), (1/2*a^4 - 5/2*a^2 + 4, 1/2*a), (1/4*a^4 - 7/4*a^2 + 13/4, -1/2*a^5 + 5/2*a^3 - 11/4*a)
```
But it is (for now) limited to convex polygons
```
sage: flatsurf.polygons(angles=[1,1,1,12])
Traceback (most recent call last):
...
ValueError: invalid 'angles' for a convex polygon
```

To find adequate lengths for given angles, one can also use the smarter
```
sage: C = flatsurf.EquiangularConvexPolygons([1,1,2,3])
sage: C
EquiangularConvexPolygons(1, 1, 2, 3) over Algebraic Real Field
sage: P = C.lengths_polytope()
sage: lengths = sum(r.vector() for r in P.rays())
sage: C(*lengths)
Polygon: (0, 0), (6.295896943239772?, 0), (4.048917339522305?, 2.817623302598764?), (1.123489801858734?, 1.408811651299382?)
```
