### ISSUE TITLE
Fix comparison and related bugs

### ISSUE THREAD

**Issue by videlec** [videlec/sage-flatsurf#22]
In order to make the package Python 3 compatible, the comparison of labels, surfaces, etc had to be modified. Some of the doctests are not working anymore and are marked with `# known bug`.

An example coming from `similarity_surface.py` (line 1710-1717) is 
```
from flatsurf import *                         
s0 = translation_surfaces.octagon_and_squares()                           
a = s0.base_ring().gens()[0]
m = Matrix([[1,2+a],[0,1]])               
s = m*s0                   
s = s.triangulate()              
ss = s.delaunay_decomposition(triangulated=True)
```
which triggers
```
Traceback (most recent call last):
...
      5 s = m*s0
      6 s = s.triangulate()
----> 7 ss = s.delaunay_decomposition(triangulated=True)   # known bug

.../flatsurf/geometry/similarity_surface.py in delaunay_decomposition(self, triangulated, delaunay_triangulated, in_place, direction, relabel)
   1755             loop=False
   1756             for (l1,e1),(l2,e2) in s.edge_iterator(gluings=True):
-> 1757                 if (l1<l2 or (l1==l2 and e1<=e2)) and s._edge_needs_join(l1,e1):
   1758                     s.join_polygons(l1, e1, in_place=True)
   1759                     loop=True

TypeError: '<' not supported between instances of 'int' and 'ExtraLabel'
```

**Comment by wphooper** [comment]
My recent commits resolve this issue.

More information: We still allow multiple label types. But there is now a helper class `LabelComparator` which places a total ordering on labels of arbitrary types. The class is in `flatsurf/geometry/surface.py`. You can get a label comparator for a SimilaritySurface using the command `s._label_comparator()`.

**Comment by videlec** [comment]
Note that I reintroduced some `# not tested` in a69a3ef because tests were failing on Travis CI.

If you reintroduce them, please make sure that all tests pass on Travis with all Sage version before merging in master.
