### ISSUE TITLE
Support flipper

### ISSUE THREAD

**Issue by wphooper** [videlec/sage-flatsurf#24]
I could not get flipper to work on Sage 9.0.

There are directions that used to work in the jupyter notebook "examples/defining_surfaces.ipynb". I am posting an update to that document which comments out flipper related examples.

**Comment by videlec** [comment]
"I could not get flipper to work on Sage 9.0" is not very informative.

**Comment by wphooper** [comment]
Apologies. 

The method I was using to install flipper was not working in Sage 9.0, but I was just now able to get it working with 
`sage -pip install flipper`
I'll post a fix to the notebook soon.
